- Readme.md
add "rename file include/config.h.example to include/config.h" to readme
> close #2; update readme

- .github/workflows/actions.yml
This action runs on every PR that is created on master to ensure that the firmware builds without critical errors.
> Added github CI for PR tests

- .github/workflows/actions.yml
- Readme.md
- platformio.ini
- prebuild.py
swig building implementation thats needed for https://github.com/Open-Smartwatch/open-smartwatch-os/issues/29
Can someone maybe test it on windows? i have currently no access to a running windows machine :D 
I'm not sure if the paths also work on windows like this is built. If there are any problems i can also implement a additional switch for that.
> implemented swig build and updated ci and readme

- Readme.md
Added the `-t upload` option on the command line
This PR fixes issue #36
> Added upload option in Readme

- include/apps/tools/water_level.h
- src/apps/tools/water_level.cpp
Add a bar display to the water level screen, switch the screen by pressing lower right button
> Feat : water level screens

- include/apps/tools/water_level.h
- src/apps/tools/water_level.cpp
Add verbose code
Use more consts to remove magic numbers and store some values instead of calling few times the same functions
> refactor: simplify the water level app and remove the magic numbers

- include/osw_hal.h
- src/hal/time.cpp
I wanted to use the date in a watch face and thought I might not be the only one.
> Add a function to get the day of the week and day of the month

- include/osw_hal.h
- src/hal/display.cpp
A simple getter function to return the screen brightness
> Add a function to expose screen brightness to user

- include/apps/lua/mylua_example.h
- include/apps/main/luaapp.h
- src/apps/main/luaapp.cpp
- src/swig/osw.i
1. SWIG wrap stdint so types are correct
2. Change example lua script to be the stopwatch code
3. Print Lua errors for more helpful messages
> Fix Lua Osw Crash

- Readme.md
- include/config.h.example
Added troubleshooting section to readme and added some extra commenting to config example.
> Added troubleshooting section to readme and extra commenting to config example

- include/apps/main/watchface_digital.h
- include/config.h.example
- include/locales/de-DE.h
- include/locales/en-US.h
- include/osw_hal.h
- src/apps/main/watchface_digital.cpp
- src/hal/time.cpp
- src/main.cpp
This introduces a digital watchface which supports 12 and 24 hour time formats.
This PR addresses comments from the original, https://github.com/Open-Smartwatch/open-smartwatch-os/pull/58
> refactored per pr comments

- include/config.h.example
- src/apps/main/watchface_digital.cpp
- src/hal/time.cpp
This will allow the date display (currently only available on the digital watchface) to be configured one of two ways
> configurable date

- data/lua/apps/stopwatch.lua
- data/lua/libs/graphicsUtils.lua
- include/apps/main/luaapp.h
- include/hal/esp32/spiffs_filesystem.h
- include/hal/osw_filesystem.h
- include/osw_hal.h
- src/apps/main/luaapp.cpp
- src/hal/esp32/spiffs_filesystem.cpp
- src/hal/filesystem.cpp
- src/main.cpp
Sets up SPIFFS and enables lua scripts (and inclue/required modules) to be loaded from the virtual filesystem
> Lua filesystem

- include/apps/tools/button_test.h
- include/osw_hal.h
- src/apps/tools/button_test.cpp
- src/hal/buttons.cpp
- src/main.cpp
Added Methods for Buttons like Game Engine do:
` // Buttons (Engine-Style)
bool btnHasGoneDown(uint8_t btn);
bool btnHasGoneUp(uint8_t btn);
bool btnIsPhysicalDown(uint8_t btn);
bool btnIsLongPress(uint8_t btn);`
U can now easy acess events in your app-loop like:
`if(hal->btnHasGoneDown(2)){
startMyAction();
}`
Added a small app to test the events.
Issue: #67
> Button handling

- include/apps/main/switcher.h
- src/apps/main/switcher.cpp
- src/main.cpp
- src/overlays/overlays.cpp
As far as my testing goes everything works fine :)
#55
> App switcher

- include/apps/main/watchface_binary.h
- src/apps/main/watchface_binary.cpp
- src/main.cpp
Well as nobody did this until now and i think this projects needs something like this :)
> Binaryface

- include/locales/cs-CZ.h
Added Czech translation
Without diacritics
> Czech translation

- include/osw_hal.h
- src/hal/sensors_accelerometer_bma400.cpp
- src/hal/statistics_steps.cpp
- src/hal/time.cpp
Hi,
as mentioned in discord!
cheerz,
Max
> hot fix for stepsstatistics

- include/apps/main/stopwatch.h
- src/apps/main/stopwatch.cpp
* added laps (max 4x7=28)
* changed UI (used #20 as inspiration)
> Updated Stopwatch

- include/locales/ko-KR.h
I added a ko.KR.h file to the include/locale path.
> Add : Language korean ko-KR.h

- include/apps/tools/time_config.h
- include/osw_ui.h
- src/apps/games/brick_breaker.cpp
- src/apps/games/snake_game.cpp
- src/apps/main/stopwatch.cpp
- src/apps/tools/OswAppWebserver.cpp
- src/apps/tools/time_config.cpp
- src/main.cpp
- src/osw_ui.cpp
- src/services/OswServiceTaskWebserver.cpp
For #161 
Also integrated into OTA webserver
> Feature/more UI

- include/locales/ko-KR.h
I added the language file in the master branch to the develop branch.
```
include/locales/ko-KR.h
```
> Migration : Language korean ko-KR.h

- Readme.md
> Update : readme

- src/main.cpp
Refactor : Delete the <hal> param
Updated code status when building to take screenshots for watch.
> Update : screenserver_loop() argument

- src/apps/watchfaces/watchface.cpp
Reduce code capacity by preprocessing libraries
> apps/watchfaces : add preprocessing for MATRIX library

- include/osw_config_keys.h
- src/hal/environment.cpp
- src/osw_config_keys.cpp
The number of steps is not initialized.
(See https://github.com/Open-Smartwatch/open-smartwatch-os/issues/188)
> Add reset timing

- src/apps/watchfaces/watchface.cpp
* Improved stepHistory-frame and stepHistory-Arc overlap in `Watchface.cpp`.
* Improve the areas that are disturbed by the background of the text.
> Apps/watchfaces : fix overlap in Watchface

- include/apps/watchfaces/watchface_digital.h
- include/apps/watchfaces/watchface_mix.h
- src/apps/watchfaces/watchface_digital.cpp
- src/apps/watchfaces/watchface_mix.cpp
- src/main.cpp
- src/osw_config_keys.cpp
Hello World !
Finally, I will update the new watchface.
* Update Watchface-MIX
* Algorithm update due to addition of new date format
* Some update in OSW-config
See : https://github.com/Open-Smartwatch/open-smartwatch-os/issues/197
> Apps/watchfaces : Update Watchface-MIX

- src/apps/watchfaces/watchface.cpp
fixed https://github.com/Open-Smartwatch/open-smartwatch-os/issues/201
> Watchface : fixed #201

- include/osw_config_keys.h
- src/apps/watchfaces/watchface.cpp
- src/osw_config_keys.cpp
See #207 
Notification of step-counter ( Today / Total / Goal )
> Apps : display goal steps ( Today / Total / Goal )

- .github/buildEverything.py
- platformio.ini
Perform a test build about all models supported in `platformio.ini`
> CI : compile all models

- .github/buildEverything.py
- .github/workflows/test-OSW.yml
Analyze detailed CI results based on one language and one model. The time was reduced to around *8 minutes*.
> CI : reduce time and analyze detailed results

- .github/workflows/astyle.yml
> Added astyle workflow

- include/apps/watchfaces/OswAppWatchfaceDual.h
- src/apps/tools/OswAppFitnessStats.cpp
- src/apps/watchfaces/OswAppWatchfaceDual.cpp
Mark as success-color when the goal is achieved.
> OswAppWatchfaceDual : fix data type in progress bar

- include/hal/environment.h
- src/apps/tools/OswAppKcalStats.cpp
- src/apps/tools/OswAppStepStats.cpp
- src/hal/environment.cpp
> HAL : refactoring calculate steps

- include/apps/watchfaces/OswAppWatchfaceDual.h
- src/apps/tools/OswAppKcalStats.cpp
- src/apps/tools/OswAppStepStats.cpp
- src/apps/watchfaces/OswAppWatchfaceDual.cpp
- src/apps/watchfaces/OswAppWatchfaceFitness.cpp
- src/apps/watchfaces/OswAppWatchfaceMix.cpp
> Apps : refactoring variable value

- include/apps/tools/OswAppFitnessStats.h
- include/apps/tools/OswAppKcalStats.h
- include/apps/tools/OswAppStepStats.h
- include/apps/tools/OswAppWebserver.h
- include/apps/tools/ble_media_ctrl.h
- include/apps/tools/button_test.h
- include/apps/tools/print_debug.h
- include/apps/tools/time_config.h
- include/apps/tools/water_level.h
- include/apps/watchfaces/OswAppWatchface.h
- include/apps/watchfaces/OswAppWatchfaceBinary.h
- include/apps/watchfaces/OswAppWatchfaceDigital.h
- include/apps/watchfaces/OswAppWatchfaceDual.h
- include/apps/watchfaces/OswAppWatchfaceFitness.h
- include/apps/watchfaces/OswAppWatchfaceMix.h
Prevent Header Duplicate Declaration.
> Apps : prevent header duplicate declaration

- src/apps/watchfaces/OswAppWatchfaceMix.cpp
See https://github.com/Open-Smartwatch/open-smartwatch-os/pull/237#discussion_r896417411
> OswAppWatchfaceMix : replace variable

- include/apps/watchfaces/OswAppWatchfaceDual.h
- src/apps/tools/OswAppKcalStats.cpp
- src/apps/tools/OswAppStepStats.cpp
Delete some comments(irrelevant).
> Remove comment

- include/hal/environment.h
- src/hal/environment.cpp
We can bring the data 7 days ago.
> HAL : add get last-week steps in environment

- src/apps/tools/OswAppStepStats.cpp
> OswAppStepStats : replace value

- include/apps/watchfaces/OswAppWatchface.h
- src/apps/watchfaces/OswAppWatchface.cpp
I changed it to an integrated meaning.
> Replace matrix to animation word

- .github/buildEverything.py
- .github/workflows/test-FEATURE.yml
Added for check CI for unused functions.
> CI check the unused flag

- include/services/OswServiceTasks.h
Remove code
```
class OswServiceTaskRawScreenServer;
```
> OswServiceTasks  : no longer in use

- .github/buildEverything.py
- .github/workflows/test-OSW.yml
Beta version that allows LE to be deployed.
Feel free to give me your opinion :+1:
> CI : add BLE github action

- CONTRIBUTING.md
See https://github.com/Open-Smartwatch/open-smartwatch-os/issues/259
> CONTRIBUTING : add CONTRIBUTING docs, close #259

- include/apps/main/switcher.h
- include/config_defaults.h
- include/osw_config_keys.h
- include/osw_hal.h
- src/apps/main/stopwatch.cpp
- src/apps/main/switcher.cpp
- src/hal/buttons.cpp
- src/osw_config_keys.cpp
Replacement for #258 because I'm an idiot and cleared the other PR by @FranseFrikandel .
>  Setting Button (TimeOut) Through the Web Interface

- include/apps/tools/OswAppDistStats.h
- include/apps/tools/OswAppStepStats.h
- include/locales/cs-CZ.h
- include/locales/de-DE.h
- include/locales/en-US.h
- include/locales/fr-FR.h
- include/locales/hu-HU.h
- include/locales/it-IT.h
- include/locales/ko-KR.h
- src/apps/tools/OswAppDistStats.cpp
- src/apps/tools/OswAppKcalStats.cpp
- src/apps/tools/OswAppStepStats.cpp
- src/main.cpp
* Add Distance stats
* Update rename Kcal-stats title
* Update info-panel (Avg, total..)
> Update Fitness APP

- src/apps/main/switcher.cpp
Fixed Lightsleep not working properly with really really long enough button press as it switches to the next app because doSwitch is still true form LONG_PRESS.
> Fixed Lightsleep not working properly

- include/apps/tools/OswAppStepStats.h
- src/apps/tools/OswAppDistStats.cpp
- src/apps/tools/OswAppFitnessStats.cpp
- src/apps/tools/OswAppKcalStats.cpp
- src/apps/tools/OswAppStepStats.cpp
> Fitness-APP : refactoring info-panel

- .github/setMatrix.sh
- .github/workflows/test-FEATURE.yml
- .github/workflows/test-OSW.yml
With #246
Replace some commands with a script.
> CI : refactoring action with script

- include/apps/tools/OswAppCalendar.h
- src/apps/tools/OswAppCalendar.cpp
Add Calendar APP
-Resolve #152
> Add OSW-APP for Calendar

- include/apps/tools/OswAppBLEMediaCtrl.h
- src/apps/tools/OswAppBLEMediaCtrl.cpp
> OswAppBLEMediaCtrl: typo in file

- include/config_defaults.h
This is just a small fix. The lack of it confused me and also multiple others I've showed this repo to.
> fix list of date possibilities

- include/apps/watchfaces/OswAppWatchfaceMonotimer.h
- src/apps/watchfaces/OswAppWatchfaceMonotimer.cpp
- src/main.cpp
- src/osw_config_keys.cpp
Hi!
I've created a monotimer watchface.
Would be nice if you review and (maybe) merge it.
Cheers,
David
> Add Monotimer Watchface

- emulator/include/Emulator.hpp
- emulator/src/Emulator.cpp
- include/osw_config.h
- src/osw_config.cpp
> Emulator: add web interface virtual mode

- include/osw_hal.h
- src/apps/watchfaces/OswAppWatchface.cpp
- src/hal/buttons.cpp
~~TEST sample code~~
Just use 
```
hal->btnIsDoubleClick(BUTTON_N)
```
> DoubleClick: add double-click

- include/devices/esp32.h
- include/services/OswServiceTaskWiFi.h
- src/devices/esp32.cpp
- src/services/OswServiceTaskWiFi.cpp
Also replaces #308 - sorry, only saw this PR just now...
> Fix for #307

- .github/workflows/astyle.yml
Auto formatting working only upstream OSW-OS repository.
> CI: only working original upstream repository

- include/apps/tools/OswAppWebserver.h
- src/apps/tools/OswAppWebserver.cpp
> Update connectionInfo method

- src/apps/watchfaces/OswAppWatchface.cpp
- src/apps/watchfaces/OswAppWatchfaceDual.cpp
- src/apps/watchfaces/OswAppWatchfaceFitness.cpp
- src/apps/watchfaces/OswAppWatchfaceNumerals.cpp
- hard coding value
- if statement
> some refactoring

- include/hal/environment.h
- src/hal/environment.cpp
- src/osw_hal.cpp
> Bugfix for #200

- CMakeLists.txt
- emulator/include/Emulator.hpp
- emulator/src/Emulator.cpp
- include/apps/main/switcher.h
- include/apps/tools/OswAppDistStats.h
- include/apps/tools/OswAppKcalStats.h
- include/apps/tools/OswAppPrintDebug.h
- include/osw_app.h
- src/apps/main/switcher.cpp
- src/apps/tools/OswAppDistStats.cpp
- src/apps/tools/OswAppKcalStats.cpp
- src/apps/tools/OswAppPrintDebug.cpp
- src/osw_ui.cpp
Allows devs to easier manipulate the internal state of the applications (during development).
> Added debug overlay into emulator

- include/gfx_2d.h
Relocation of structure according to if statement life range.
> gfx_2d: relocation of if statement

- CMakeLists.txt
- include/apps/tools/OswAppCalculator.h
- include/apps/tools/OswAppFlashLight.h
- include/config_defaults.h
- src/apps/tools/OswAppCalculator.cpp
- src/apps/tools/OswAppFlashLight.cpp
- src/main.cpp
Add OswAppCalculator
That is my first pull request, I hope everything is right ;)
> Add calculator and flash-light

- Readme.md
Would resolve https://github.com/Open-Smartwatch/open-smartwatch-os/issues/326 if merged
> docs: Adds license to readme

- .github/buildEverything.py
- .github/workflows/astyle.yml
- .github/workflows/test-EMULATOR.yml
- .github/workflows/test-FEATURE.yml
- .github/workflows/test-OS.yml
- .github/workflows/test-OSW.yml
- include/locales/ko-KR.h
> CI: refactoring all CI action

- src/hal/environment.cpp
> Fix for #344

- .github/workflows/test-EMULATOR.yml
- .github/workflows/test-FEATURE.yml
- .github/workflows/test-OS.yml
- .github/workflows/test-OSW.yml
Grrr - this mistake costed me `5$`...
> Switched to cached LFS workflows to reduce bandwidth impact

- emulator/include/RtcDS3231.h
- emulator/src/RtcDS3231.cpp
- include/apps/tools/OswAppFlashLight.h
- src/apps/tools/OswAppFlashLight.cpp
- src/devices/ds3231mz.cpp
- Constant brightness application anymore (spams logs)
- Display turned off, while active
- Do not allow state manipulation without activity
> Minor bugs with the flashlight application :flashlight: 

- src/apps/tools/OswAppFlashLight.cpp
Fixed #386
white color, and black color
> Fixed #386, color for flashLight

- README.md
- docs/firmware/apps/OswWeather.md
- docs/firmware/apps/watchfaces.md
- docs/firmware/osw_os.md
- emulator/src/Emulator.cpp
- include/Arduino_Canvas_Graphics2D.h
- include/apps/tools/OswAppFlashLight.h
- include/config_defaults.h
- include/devices/esp32.h
- include/gfx_2d_print.h
- include/globals.h
- include/math_angles.h
- include/services/OswServiceTaskMemMonitor.h
- scripts/build/prebuild_info.py
- src/OswAppV2.cpp
- src/animations/demos/README.md
- src/apps/OswAppDrawer.cpp
- src/apps/_experiments/OswAppWeather.cpp
- src/apps/_experiments/dnatilt.cpp
- src/apps/tools/OswAppCalculator.cpp
- src/apps/watchfaces/OswAppWatchfaceDigital.cpp
- src/devices/esp32.cpp
- src/hal/power.cpp
- src/math_angles.cpp
- src/osm_render.cpp
- src/osw_ulp.cpp
- src/services/OswServiceTaskWiFi.cpp
Close #365.
Fix some typo, please check it.
- exclude libraries
> Fix typo on root project

- .github/workflows/test-OSW.yml
for compatible from upload v3 and download v3
> workflows: fix download version and change file path

- src/services/OswServiceTaskConsole.cpp
...just a quick one to debug #414
> Added notify command to quickly send notifications from console

- docs/firmware/apps/watchfaces.md
- include/apps/watchfaces/OswAppWatchfaceDigital.h
- include/config_defaults.h
- include/locales/de-DE.h
- include/locales/en-US.h
- include/osw_hal.h
- include/osw_ui.h
- src/apps/watchfaces/OswAppWatchface.cpp
- src/apps/watchfaces/OswAppWatchfaceDigital.cpp
- src/apps/watchfaces/OswAppWatchfaceFitnessAnalog.cpp
- src/hal/display.cpp
- src/osw_config_keys.cpp
- src/osw_hal.cpp
- src/osw_ui.cpp
- src/services/OswServiceTaskConsole.cpp
> A few bugs and minor issues
