src/osw_ui_util.cpp
Here is a useless PR that fixes a spelling mistake in a comment.
=> fix spelling: defaut -> default

include/config.h.example, include/osw_service.h, include/services/companionservice.h, include/services/servicemanager.h, include/services/services.h, platformio.ini, src/main.cpp, src/services/companionservice.cpp, src/services/servicemanager.cpp
Basic Bluetooth service for companion app and Notifications. I'm hoping this will be a good start to allowing the watch to pair to a Smartphone and integration.
- Creates framework for background services which are always running. Apps are able to lookup a service to call methods on them
- Sets up a Bluetooth LE watch service that can be advertised
- Adds a LE Characteristic for Notifications
- Uses ArduinoJSON to deserialize LE packet into notification details
- Sends callback to client about new notification
Repo for the companion app can be found here: https://github.com/SeanReg/open-smartwatch-android-companion
Companion app is very basic. 
Right now it will do the following:
- Scan for the Open Smartwatch service and store the first discovered device's MAC
- Setup GATT connection to …
=> BluetoothLE Service for Companion App

src/apps/main/luaapp.cpp
Force running the Garbage collector after loop function call because it can't keep up with allocations.
@uvwxy 
Mind testing this with the StopWatch Lua example? This *should* fix the crash
=> Force run the GC every loop

src/apps/main/switcher.cpp
If the deepsleep gets triggered while a button is pressed, we reset the screentime for the app.
This should avoid deepsleep while we do stuff on the watch :)
=> Prevent Deepsleep while buttons are pressed

include/config.h.example, include/osw_config_keys.h, src/hal/display.cpp, src/hal/power.cpp, src/main.cpp, src/osw_config.cpp, src/osw_config_keys.cpp
Adding new config value - minimum brightness. This is to prevent the user from setting the brightness to 0 on accident and forgetting about it. The minimum can be changed to 0 if the user would like to be able to set the brightness to 0. This change persists the brightness the user selects on-device. Might be nice to introduce some kind of helper method or something in OswConfig that handles enableWrite and disableWrite for reducing repetitive code.
Tested working fine thus far.
=> Allowing on-device brightness updates

include/config.h.example, include/osw_config_keys.h, src/apps/main/switcher.cpp, src/osw_config_keys.cpp
#131 - on sleep - button presses wake up watch from sleep by default; config.h can change this behavior to turn off.
Already a feature within develop codebase, simply exposing as config.h item and consuming in switcher.cpp
=> Issue 131 - configuration button press to wake - default on

include/locales/de-DE.h
Hi @uvwxy 
I've got my first two OSW PCBs this week and want to support the work on this project. To get started I fixed a typo in the german translation.
=> Fix German translation de-DE continue "Fortsetzen"

platformio.ini
excludes AdafruitBusIO version 1.9.7 which is incompatible with 1.x.x Arduino Espressif32 framework.
=> fixes issue #174

src/apps/watchfaces/watchface.cpp
Correct parameters for the short and long sides of the seconds
=> Apps/watchfaces : fix #213

src/apps/main/switcher.cpp
I rewrote the auto sleep timeout so it will reset the sleep timer when any button is pressed on the main watch face, instead of only checking for button presses right before it goes to sleep.
This is my first pull request, apologies if I made it wrong.
=> Fix Auto sleep Timer on Watchface from Issue #186

include/apps/tools/OswAppKcalStats.h, src/apps/tools/OswAppKcalStats.cpp
See https://github.com/Open-Smartwatch/open-smartwatch-os/pull/223#discussion_r884081507
=> KcalStats : refactoring draw-curved chart without array

include/apps/main/stopwatch.h, src/apps/main/stopwatch.cpp
Press the reset button briefly to cross-view the overall-time and laps-time.
=> Stopwatch : add overall-time measurement

include/apps/watchfaces/OswAppWatchfaceDigital.h, src/apps/watchfaces/OswAppWatchfaceDigital.cpp, src/apps/watchfaces/OswAppWatchfaceFitness.cpp, src/apps/watchfaces/OswAppWatchfaceMix.cpp
Refactoring the code below used to abbreviate the date.
```
{
char weekday3[4];
weekday3[0] = wd[0];
weekday3[1] = wd[1];
weekday3[2] = wd[2];
weekday3[3] = '\0';
}
```
=> HAL: refactoring slice-weekday

.github/workflows/test-EMULATOR.yml, .github/workflows/test-FEATURE.yml, .github/workflows/test-OSW.yml
Commands for canceling or skipping CI in some cases.
This will reduce the time by omitting the push and making only PR work.
=> CI: omit arbitrary ci

include/osw_config_keys.h
- error: 'invalid_argument' is not a member of 'std'
```
In file included from include/osw_hal.h:17:0,
from include/./apps/_experiments/autumn.h:4,
from src/apps/_experiments/autumn.cpp:2:
include/osw_config_keys.h: In static member function 'static size_t OswConfigKeyDropDown::getOptionIndex(const std::vector<const char*>&, const String&)':
include/osw_config_keys.h:245:15: error: 'invalid_argument' is not a member of 'std'
throw std::invalid_argument("Option not found in options list");
^
include/osw_config_keys.h: In member function 'void OswConfigKeyDropDown::checkValidOption(const String&)':
include/osw_config_keys.h:266:15: error: 'invalid_argument' is not a member of 'std'
throw std::invalid_argument("Invalid option value for dropdown key!");
^
In file included from …
```
=> osw_config_keys: add stdexcept libraries

.github/workflows/test-EMULATOR.yml, .github/workflows/test-FEATURE.yml, .github/workflows/test-OSW.yml
PR for branches at the same storage level takes a lot of time to check with one push and one PR. I think we can reduce this in this way.
=> CI: skip unnecessary actions

include/apps/tools/OswAppStepStats.h, src/apps/tools/OswAppStepStats.cpp
Add a debug window to 'OswAppStepStats' as well.
=> OswAppStepStats: add debug window for current position value

CMakeLists.txt, docs/firmware/apps/OswWeather.md, include/apps/_experiments/OswAppWeather.h, include/apps/_experiments/OswAppWeatherEncoder.h, src/apps/_experiments/OswAppWeather.cpp, src/apps/_experiments/OswAppWeatherEncoder.cpp
This PR is based on https://github.com/Open-Smartwatch/open-smartwatch-os/pull/376 , but the author did not authorize modifications on its fork before merge - so I forked his branch and pulled it into this PR.
=> Updated PR #376

.github/workflows/test-EMULATOR.yml, .github/workflows/test-FEATURE.yml, .github/workflows/test-OS.yml, .github/workflows/test-OSW.yml, CMakeLists.txt, README.md, docs/firmware/osw_os.md, emulator/include/Serial.h, emulator/src/Serial.cpp, emulator/src/tests/unitTests/logging.cpp, include/osw_config.h, include/services/OswServiceTaskConsole.h, include/services/OswServiceTaskExample.h, platformio.ini, src/main.cpp, src/osw_config.cpp, src/services/OswServiceTaskConsole.cpp, src/services/OswServiceTaskExample.cpp, src/services/OswServiceTaskWebserver.cpp, src/services/OswServiceTaskWiFi.cpp, src/services/OswServiceTasks.cpp
Some simple stuff to configure/reset/reboot/wipe the device without the need to setup/connect to the hotspot.
Also very useful if you disabled AutoAP, messed up the WiFi configuration and are now locked out. ALSO, much more convenient to reconfigure on-the-fly instead of recompiling all the time.
=> Added serial console

emulator/src/Emulator.cpp, include/apps/OswAppDrawer.h, include/globals.h, src/apps/OswAppDrawer.cpp, src/globals.cpp, src/main.cpp
This properly resets the drawer instance as part of the emulator reset.
=> Fix for #404

.github/workflows/astyle.yml
fix code style info -> real uer info
=> workflows: fix code style workflows user name

.github/workflows/test-OS.yml
If testing is required for binaries built by OS workflows, it must be provided by the pipeline.
=> workflows: upload firmware binary

.github/workflows/test-EMULATOR.yml, .github/workflows/test-OS.yml, .github/workflows/test-OSW.yml
upload, download-artifact plugin v3 will be deprecated, so we upgrade to v4.
=> workflows: upgrade artifact version to v4

docs/firmware/flags.md, include/config_defaults.h, include/gfx_2d_print.h, include/osw_config_keys.h, include/osw_pins.h, include/osw_ui.h, include/services/NotifierClient.h, include/services/OswServiceManager.h, include/services/OswServiceTaskBLECompanion.h, include/services/OswServiceTaskBLEServer.h, include/services/OswServiceTaskConsole.h, include/services/OswServiceTasks.h, platformio.ini, src/hal/gps.cpp, src/osw_config.cpp, src/osw_config_keys.cpp, src/osw_ui.cpp, src/services/NotifierClient.cpp, src/services/OswServiceTaskBLECompanion.cpp, src/services/OswServiceTaskBLEServer.cpp, src/services/OswServiceTaskConsole.cpp, src/services/OswServiceTaskWebserver.cpp, src/services/OswServiceTasks.cpp
After #409, part of #141 
this is JUST the server, so a device can connect to an OSW and perform a few basic operations
the client will be implemented whenever we have a spec/server for it
checklist:
=> Implemented basic BLE server

src/apps/tools/OswAppTutorial.cpp
Move variables that are compiled but may not be used due to macros into the scope of the macros.
=> Fix compile minor waring
